### ISSUE TITLE
C# SDK: FaceRectangle should inherit from Rectangle

### ISSUE THREAD

**Issue by margaretmz** [Microsoft/Cognitive-Face-Windows#1]
_From @SaqibS on November 24, 2015 18:35_

I am using the C# client SDKs available from NuGet.

When using the face detection API, you get back an array of FaceRectangles. However, the Emotion Detection API requires an array of Rectangles (from the Common namespace). Both types have the same 4 fields one would expect.

These should be consolidated - either FaceDetection should return Common Rectangles, or else FaceRectangle should inherit from Rectangle. Or, just use System.Drawing.Rectangle.

_Copied from original issue: Microsoft/ProjectOxford-ClientSDK#6_

**Comment by huxuan** [comment]
Close as deprecated. Currently, there is no plan to solve this problem.
