### ISSUE TITLE
Offer PowerShell Module as Sample Implementation

### ISSUE THREAD

**Issue by MLauper** [Microsoft/Cognitive-Face-Windows#14]
Hi all

I have written a PowerShell Module with a full implementation of the Microsoft Azure Face API. 
As described in the contribution guidelines, I would like to offer this as a sample implementation for PowerShell.

You can review my code under the following GitHub URL:
https://github.com/MLauper/ps-AzureFaceAPI/tree/master

I appreciate any feedback on this little project.

Regards,
Marco

**Comment by huxuan** [comment]
Hi @MLauper , thanks for your interests and contribution! It's really good job! We are communicating with our PMs about how to deal with this kind of stuff.

**Comment by huxuan** [comment]
Close as there is no further steps on this. Anyway, thanks for your contribution.
