### ISSUE TITLE
I can't install this nuget into a xamarin project 

### ISSUE THREAD

**Issue by pasha-o** [Microsoft/Cognitive-Face-Windows#19]
Could not install package 'Microsoft.ProjectOxford.Face 1.2.1.2'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v7.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0

**Comment by huxuan** [comment]
Hi @pasha-o, thanks for your report. But actually I don't think our windows version SDK supports MonoAndroid platform right now. I would suggest you to use the Android SDK [1] we created.

[1] https://github.com/Microsoft/Cognitive-Face-Android

**Comment by pasha-o** [comment]
hi @huxuan thanks for the response. I am targeting a crossplatform using xamarin - is there a plugin for Face to install on all platforms?

**Comment by huxuan** [comment]
Hi @pasha-o, actually I am not familiar with xamrin development. I would suggest you use REST API directly via HTTP request which should be absolutely platform independent.

**Comment by pasha-o** [comment]
thanks , i noticed ProjectOxford.Vision is nicely working in PCL and
xamarin . I thought the authors are the same or it should be easy to
migrate the Face plugin to support mono as well ....

**Comment by huxuan** [comment]
@pasha-o The only truth I can provide currently is that we are different teams. But I will keep this issue open for possible further follow up.

**Comment by pasha-o** [comment]
I really appreciate  it. Perhaps you two teams can communicate and find a
way how they did it. It brings consistency to the plug-ins.

**Comment by huxuan** [comment]
Close as there is no plan for xamarin support currently.
