### ISSUE TITLE
Endpoint change

### ISSUE THREAD

**Issue by SuperJMN** [Microsoft/Cognitive-Face-Windows#22]
I have received an e-mail notification saying that the current endpoint will stop working tomorrow. I'm afraid that my application using Face API will stop working as well.

My application is using Face API through the client in this NuGet package: https://www.nuget.org/packages/Microsoft.ProjectOxford.Face/

What should I do to avoid problems with the upcoming change?

Thanks

**Comment by marcominerva** [comment]
You need to specify the new endpoint in the FaceServiceClient constructor:

`var faceService = new FaceServiceClient(Settings.FaceSubscriptionKey, "https://westus.api.cognitive.microsoft.com/face/v1.0");`

**Comment by huxuan** [comment]
Actually, we have merged the pull request #20 for endpoint change, but it seems that the nuget package on nuget.org is not updated. I will check with my colleagues on fixing this problem ASAP. Currently, you can follow @marcominerva 's suggestion to ensure it works. I will keep this issue open until new package are updated on nuget.org.

**Comment by huxuan** [comment]
Close as version 1.2.5 [1] has been published on nuget.

[1] https://www.nuget.org/packages/Microsoft.ProjectOxford.Face/1.2.5
