### ISSUE TITLE
Face Detection Issue

### ISSUE THREAD

**Issue by md-jamal** [Microsoft/Cognitive-Face-Windows#28]
When I am showing my face using the image stored in my phone to Web Camera. It still detects as a face.. Is there any way to avoid that.. Only detect 3D Faces, not from mobile phone

**Comment by huxuan** [comment]
AFAIK, anti-spoofing not only depends on algorithm adaptation, but also need hardware cooperation, e.g. infrared camera which can detect distance. So it is hard for a general API which accepts image as input to be able to achieve that. Closed as explained.
