### ISSUE TITLE
Microsoft.ProjectOxford.Face.FaceAPIException' occurred in mscorlib.dll but was not handled in user code".

### ISSUE THREAD

**Issue by Letcoding** [Microsoft/Cognitive-Face-Windows#29]
when I used face similar for number of images appear this error:
 "An exception of type 'Microsoft.ProjectOxford.Face.FaceAPIException' occurred in mscorlib.dll but was not handled in user code".
How can I solve it?

**Comment by huxuan** [comment]
Hi @Letcoding , Can you get the specific error information?

**Comment by Letcoding** [comment]
Hi
I tried to run the 'face find similar' and I loaded 100 face candidate (for
example). Then I update the code of 'open quary face' to run more than one
quary at one run so I did looping. The error appear after iteration 8 or 9
as shown in attached file.
the code is :
           StreamWriter f1 = new
StreamWriter(@"C:\DATABASE\finalExp\MatchPerson.txt");
            StreamWriter f2 = new
StreamWriter(@"C:\DATABASE\finalExp\MatchFace.txt");
            ///////////////////hiba delete/////
            // Show file picker
            //Microsoft.Win32.OpenFileDialog dlg = new
Microsoft.Win32.OpenFileDialog();
            //dlg.DefaultExt = ".jpg";
            //dlg.Filter = "Image files (*.jpg, *.png, *.bmp, *.gif) |
*.jpg; *.png; *.bmp; *.gif";
            //var filePicker = dlg.ShowDialog();


            ///////////////////////hiba//////////////////
           // string pp = @"C:\DATABASE\finalExp\Accessories
Results\Accessory Orignal";
            string[] allfiles =
Directory.GetFiles(@"C:\DATABASE\finalExp\Accessories Results\New");
            for (int i = 0; i < allfiles.Length; i++)
            {






                //if (filePicker.HasValue && filePicker.Value)
                //{
                    // User picked image
                    // Clear previous detection and find similar results
                    TargetFaces.Clear();
                FindSimilarMatchPersonCollection.Clear();
                FindSimilarMatchFaceCollection.Clear();
                var sw = Stopwatch.StartNew();
                //SelectedFile = dlg.FileName;
                ///////////hiba///////////
                SelectedFile = allfiles[i];
                ////////////////////////////////////
                var imageInfo =
UIHelper.GetImageInfoForRendering(SelectedFile);

                // Detect all faces in the picked image
                using (var fileStream = File.OpenRead(SelectedFile))
                {
                    MainWindow.Log("Request: Detecting faces in {0}",
SelectedFile);

                    MainWindow mainWindow = Window.GetWindow(this) as
MainWindow;
                    string subscriptionKey =
mainWindow._scenariosControl.SubscriptionKey;

                    var faceServiceClient = new
FaceServiceClient(subscriptionKey);
                    var faces = await
faceServiceClient.DetectAsync(fileStream);

                    // Update detected faces on UI
                    foreach (var face in
UIHelper.CalculateFaceRectangleForRendering(faces, MaxImageSize, imageInfo))
                    {
                        TargetFaces.Add(face);

                    }

                    MainWindow.Log("Response: Success. Detected {0} face(s)
in {1}", faces.Length, SelectedFile);


                    //////////////////hiba
                    /// here write in text file the test ID and set var
Chk=0 after for loop check the Chk
                    /// if ==0 then write in text file "No match"
                    string ss;

                    int xx = SelectedFile.IndexOf('0');
                    ss = SelectedFile.Substring(xx, 6);
                    f1.Write(ss);
                    f1.Write("     ");
                    f2.Write(ss);
                    f2.Write("     ");
                    int Chk = 0;
                    //////////////////////////////////////
                    // Find two modes similar faces for each face
                  foreach (var f in faces)
                    {
                        var faceId = f.FaceId;

                        MainWindow.Log("Request: Finding similar faces in
Personal Match Mode for face {0}", faceId);

                        try
                        {
                            // Default mode, call find matchPerson similar
REST API, the result contains all the face ids which is personal similar to
the query face
                            const int requestCandidatesCount = 4;
                            var result = await
faceServiceClient.FindSimilarAsync(faceId, _faceListName,
requestCandidatesCount);

                            // Update find matchPerson similar results
collection for rendering
                            var personSimilarResult = new
FindSimilarResult();
                            personSimilarResult.Faces = new
ObservableCollection<Face>();
                            personSimilarResult.QueryFace = new Face()
                            {
                                ImagePath = SelectedFile,
                                Top = f.FaceRectangle.Top,
                                Left = f.FaceRectangle.Left,
                                Width = f.FaceRectangle.Width,
                                Height = f.FaceRectangle.Height,
                                FaceId = faceId.ToString(),
                            };
                            var Rnk = 1;
                            foreach (var fr in result)
                            {
                                var candidateFace =
FacesCollection.First(ff => ff.FaceId == fr.PersistedFaceId.ToString());
                                Face newFace = new Face();
                                newFace.ImagePath =
candidateFace.ImagePath;
                                newFace.Confidence = fr.Confidence;
                                newFace.FaceId = candidateFace.FaceId;
                                personSimilarResult.Faces.Add(newFace);
                                ///////////hiba//////////////////
                                string s;

                                int yy =
candidateFace.ImagePath.IndexOf('0');
                                s = candidateFace.ImagePath.Substring(yy,
6);
                                f1.Write(s);
                                f1.Write("     ");
                                f1.Write(fr.Confidence);
                                f1.Write("     ");
                                f1.Write(Rnk);
                                f1.Write("     ");
                                Rnk++;
                              //////////////////////////////////////////////

                            }
                            Chk = 1;
                            MainWindow.Log("Response: Found {0} similar
faces for face {1}", personSimilarResult.Faces.Count, faceId);


FindSimilarMatchPersonCollection.Add(personSimilarResult);



                        }
                        catch (FaceAPIException ex)
                        {
                            MainWindow.Log("Response: {0}. {1}",
ex.ErrorCode, ex.ErrorMessage);
                        }

                        try
                        {
                            // Call find facial match similar REST API, the
result faces the top N with the highest similar confidence
                            const int requestCandidatesCount = 4;
                            var result = await
faceServiceClient.FindSimilarAsync(faceId, _faceListName,
FindSimilarMatchMode.matchFace, requestCandidatesCount);

                            // Update "matchFace" similar results
collection for rendering
                            var faceSimilarResults = new
FindSimilarResult();
                            faceSimilarResults.Faces = new
ObservableCollection<Face>();
                            faceSimilarResults.QueryFace = new Face()
                            {
                                ImagePath = SelectedFile,
                                Top = f.FaceRectangle.Top,
                                Left = f.FaceRectangle.Left,
                                Width = f.FaceRectangle.Width,
                                Height = f.FaceRectangle.Height,
                                FaceId = faceId.ToString(),
                            };
                            var Rnk = 1;
                            foreach (var fr in result)
                            {
                                var candidateFace =
FacesCollection.First(ff => ff.FaceId == fr.PersistedFaceId.ToString());
                                Face newFace = new Face();
                                newFace.ImagePath = candidateFace.ImagePath;
                                newFace.Confidence = fr.Confidence;
                                newFace.FaceId = candidateFace.FaceId;
                                faceSimilarResults.Faces.Add(newFace);

                                //////////////////Hiba//////////////////////
                                string s1;

                                int zz =
candidateFace.ImagePath.IndexOf('0');
                                s1 = candidateFace.ImagePath.Substring(zz,
6);
                                f2.Write(s1);
                                f2.Write("     ");
                                f2.Write(fr.Confidence);
                                f2.Write("     ");
                                f2.Write(Rnk);
                                f2.Write("     ");
                                Rnk++;
                            }

                            MainWindow.Log("Response: Found {0} similar
faces for face {1}", faceSimilarResults.Faces.Count, faceId);


FindSimilarMatchFaceCollection.Add(faceSimilarResults);
                            //hiba
                           // file1.WriteLine(faceSimilarResults);
                        }
                        catch (FaceAPIException ex)
                        {
                            MainWindow.Log("Response: {0}. {1}",
ex.ErrorCode, ex.ErrorMessage);
                        }
                    }
                    if (Chk == 0)
                    {
                        f1.Write("NUN");
                        f1.WriteLine("");
                        f2.Write("NUN");
                        f2.WriteLine("");

                    }
                    else
                    {
                        f1.WriteLine("");
                        f2.WriteLine("");
                    }

                }
            }
            GC.Collect();
            f1.Close();
            f2.Close();

        }

please really I need your help because my research depended on microsoft
results.

Kind regards,
Hiba

2017-05-03 3:15 GMT+01:00 Xuan Hu (Sean) <notifications@github.com>:

**Comment by huxuan** [comment]
I mean you can try catch the exception about the specific error embedded in the exception.

**Comment by Letcoding** [comment]
How can I do that, please?


2017-05-03 10:27 GMT+01:00 Xuan Hu (Sean) <notifications@github.com>:

**Comment by Letcoding** [comment]
Hi this error:

Microsoft.ProjectOxford.Face.FaceAPIException was unhandled by user code
  ErrorCode=RateLimitExceeded
  ErrorMessage=Rate limit is exceeded. Try again later.
  HResult=-2146233088
  Message=Exception of type 'Microsoft.ProjectOxford.Face.FaceAPIException'
was thrown.
  Source=Microsoft.ProjectOxford.Face
  StackTrace:
       at
Microsoft.ProjectOxford.Face.FaceServiceClient.<SendRequestAsync>d__67`2.MoveNext()
    --- End of stack trace from previous location where exception was
thrown ---
       at
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
       at
Microsoft.ProjectOxford.Face.FaceServiceClient.<DetectAsync>d__29.MoveNext()
    --- End of stack trace from previous location where exception was
thrown ---
       at
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at
Microsoft.ProjectOxford.Face.Controls.FaceFindSimilarPage.<FindSimilar_Click>d__28.MoveNext()
in
C:\microsoft\Cognitive-Face-Windows-master\Sample-WPF\Controls\FaceFindSimilarPage.xaml.cs:line
270
  InnerException:


2017-05-03 10:30 GMT+01:00 HIBA ALKAWAZ <hibaalkawaz@gmail.com>:

**Comment by huxuan** [comment]
The error message is clear enough. You are exceeding the call rate limit. Free subscription only allow `Up to 20 transactions per minute` and `30,000 transactions free per month`. Will close this issue as this is not a service bug.

**Comment by Letcoding** [comment]
Hi
Although I gave it 10 images will stop too (this not 20 transaction per
minute).???



Further, If I would like to get more than this limitation where I go to
increase it???

Thanks for your help

2017-05-03 10:44 GMT+01:00 Xuan Hu (Sean) <notifications@github.com>:

**Comment by huxuan** [comment]
It might be other kind of errors or because you have already send more than 10 images before send current bunch of 10.

To increase the limitation, you can buy the standard tier.

Thread locked as this is not the right place for asking this kind of problems.
