### ISSUE TITLE
SampleUserControlLibrary missing in solution

### ISSUE THREAD

**Issue by rrvenki** [Microsoft/Cognitive-Face-Windows#30]
Opening the solution FaceAPI-WPF-Samples.sln has two projects. Project "FaceAPI-WPF-Samples" opens fine. Project "SampleUserControlLibrary" fails to load as it is not found in the respective location.

Please check the zip file or give right steps to use.

**Comment by huxuan** [comment]
Its a submodule and you need to `git submodule init && git submodule update` to make it work. Feel free to reopen this issue if you have any further related problems.

**Comment by boooooommmmmm** [comment]
A easier solution is simply to copy all files from [here](https://github.com/Microsoft/Cognitive-Common-Windows/tree/10b0875f4f984186db45ec6da987617dd967d14f) to `Cognitive-Common-Windows` folder
