### ISSUE TITLE
Access denied due to invalid subscription key. Make sure you are subscribed to an API you are trying to call and provide the right key

### ISSUE THREAD

**Issue by ramseen** [Microsoft/Cognitive-Face-Windows#31]
I subscribed to Face API using the subscription key for the trial version. But I am unable to make the rest api call as I getting the following JSON :   
{
  "error": {
    "code": "Unspecified",
    "message": "Access denied due to invalid subscription key. Make sure you are subscribed to an API you are trying to call and provide the right key."
  }
}
This was tried out in face api console in API reference. The same error is seen in the c# code as well.  Kindly please help

PS:  I used the correct subscription key that was assigned to me for this particular app.

**Comment by huxuan** [comment]
Please ensure you are using the subscription key with correct endpoint region which is default to `westus`.

**Comment by ramseen** [comment]
i used both westus and southasia end points but none of them are working properly ,  i tried hit on this end point with the header :  {"Ocp-Apim-Subscription-Key":"3**************************"} 
https://southeastasia.api.cognitive.microsoft.com/face/v1.0/detect?returnFaceId=true&returnFaceLandmarks=false

**Comment by huxuan** [comment]
where do you get the subscription key? They should belongs to specific region when you generate it.
If you got it from `Free Trial` on ACOM [1], it should belongs to `westcentralus`.

[1] https://azure.microsoft.com/en-us/try/cognitive-services/?api=face-api

**Comment by ramseen** [comment]
yeah i generated from that link , 
https://westcentralus.api.cognitive.microsoft.com/face/v1.0/detect?  , this end point working now :) :+1:

**Comment by huxuan** [comment]
Close as problem resolved.
