### ISSUE TITLE
Cognitive services URL should be configurable

### ISSUE THREAD

**Issue by gzepeda** [Microsoft/Cognitive-Face-Windows#33]
I was testing the WPF to see some sample code for a Xamarin App and I could not get my API key working. I noticed the different regions you could use and I saw on the Face Detection DLL (Microsoft.ProjectOxford.Face) you have the URL hardcoded on the file FaceServiceClient.cs. 

I had to recreate the service on Azure and put it on westus to get the WPF app working. 

It would be nice that this parameter could be configurable from the client.

**Comment by huxuan** [comment]
@gzepeda For SDK, there are two kinds of initialization for `FaceServiceClient` and the other one support endpoint configuration, please refer to the code here [1]. For the WPF sample, we are already working on that, please be a little bit patient. You may refer to some progress here [2].

[1] https://github.com/Microsoft/Cognitive-Face-Windows/blob/1.3.0/ClientLibrary/FaceServiceClient.cs#L176
[2] https://github.com/Microsoft/Cognitive-Common-Windows/pull/8

**Comment by gzepeda** [comment]
Thanks for the quick reply. I will use the other initialization method for the Xamarin App.

**Comment by huxuan** [comment]
Close as problem resolved.
