### ISSUE TITLE
Image too small or too big?

### ISSUE THREAD

**Issue by pec1985** [Microsoft/Cognitive-Face-Windows#38]
Hello!
Trying to detect a face, I always get the same error. I have no clue on what I am doing wrong. When I google for this, I find nothing on the C# API. 

`Image too small or too big`

I believe this is a bug in this client API

Some of my code:
```
private void DoSomething(SoftwareBitmap original, BitmapBounds bounds) 
{
	using (var inputStream = new InMemoryRandomAccessStream())
	{
		using (var converted = SoftwareBitmap.Convert(original, BitmapPixelFormat.Rgba16))
		{
			var encoder = await BitmapEncoder.CreateAsync(BitmapEncoder.PngEncoderId, inputStream);
			encoder.SetSoftwareBitmap(converted);
			// Comment this line, no difference
			encoder.BitmapTransform.Bounds = bounds;
			await encoder.FlushAsync();

			// Display the image in my window
			BitmapImage xamlImage = new BitmapImage();
			xamlImage.SetSource(inputStream);
			await Dispatcher.RunAsync(Windows.UI.Core.CoreDispatcherPriority.High, () => {
			    m_FacePreviewImage.Source = xamlImage;
			});

			// ============================================================
			// Here it is!
			// ============================================================
			var client = new FaceServiceClient("______KEY___HERE______");
			Face[] guids;
			try
			{
			    guids = await client.DetectAsync(inputStream.AsStream());
			} catch (FaceAPIException er)
			{
			    Debug.WriteLine("Exception: " + er.ErrorMessage);
			    return;
			}
			// More code...
		}
	}
}
```

**Comment by huxuan** [comment]
Hi @pec1985 , please use stackoverflow for corresponding support as mentioned in README [1]. This is more like a usage problem and there is more people support there.

[1] https://github.com/Microsoft/Cognitive-Face-Windows#contributing

**Comment by pec1985** [comment]
Thanks, @huxuan. I'll ask for help in Stackoverflow. The main idea of opening an issue was also to ask for a better ErrorMessage description. If the image is too small or too big, which one is it? and what size would it be?

I'll go to Stackoverflow.
Thanks.

**Comment by huxuan** [comment]
Hi @pec1985, thanks for the clarification. As that will be a server side change rather than SDK issue, I will take a note on our team board and  change it in the future. Thanks for your interest on Face API and feel free to update if you have any further request.
