### ISSUE TITLE
Merge with https://github.com/Microsoft/Cognitive-Face-DotNetCore and target .net standard

### ISSUE THREAD

**Issue by SychevIgor** [Microsoft/Cognitive-Face-Windows#39]
Please, merge 2 repos to avoid code copy-paste... code is 100% the same in both repos except of samples...

**Comment by huxuan** [comment]
Thanks for the information. Actually, I do not know there exists a DotNetCore SDK until seeing this issue. It should be some kind of team cooperation problem. I will keep this issue open for tracking. Sorry for the inconvenience.

**Comment by danzel** [comment]
Please see https://github.com/Microsoft/Cognitive-Common-Windows/pull/10 and https://github.com/Microsoft/Cognitive-Face-Windows/pull/43 to resolve this :+1:
