### ISSUE TITLE
Misleading error message

### ISSUE THREAD

**Issue by IrisClasson** [Microsoft/Cognitive-Face-Windows#40]
Two suggestions in regards to the following error:
Access denied due to invalid subscription key. Make sure you are subscribed to an API you are trying to call and provide the right key.

1. 'Subscription key' is easily mistaken for subscription ID, service key or API key might be better.

2. The endpoint defaults to westus, and when a client is created with just the subsciption key the client will use the default endpoint. We should either not provide a default endpoint and instead require one when the client is instantiated, or at least suggest in the error message that the endpoint might be wrong

**Comment by huxuan** [comment]
Hi @IrisClasson, thanks for your suggestions.

For the first problem, `Subscription Key` is a terminology in Cognitive Services so I am afraid we will not change it though I do admit it is ambiguous when considering the subscription id of Azure.

For the second problem, we will consider to provide more specific error message in the new version, I will keep this issue open until then.

**Comment by huxuan** [comment]
Close since there is no further response. Please feel free to reopen or create a new one if there is any other questions.
