### ISSUE TITLE
Is the face api sdk supported on .net core? (QUESTION)

### ISSUE THREAD

**Issue by Hyjaz** [Microsoft/Cognitive-Face-Windows#42]
Is the Face API sdk supported on .net core?

When I download the sdk with nuget, it says that the package was restored using .NET Framework 4.x.x instead of .NETCoreApp 2.0.

Does this mean it is not supported?

**Comment by huxuan** [comment]
I am afraid it is not supported currently. Actually I have not survey on the .Net Core compatibility yet, although the code base itself might already support .Net Core as it is only a thin wrapper of httpclient.

**Comment by Hyjaz** [comment]
Oh, ok I will try it. If it doesn't work, can I use your code on my project and make .net core compatible? @huxuan

**Comment by huxuan** [comment]
Yep, the SDK code do have license clarified, so just follow it should be OK. And it would be great if we can see any contribution to better the compatibility. I suspect it might be nuget packaging command change rather than real code base change. Anyway, any related information are welcome.

**Comment by huxuan** [comment]
Close as question answered. And Feel free to open new issues or reopen this one if you have any further questions.
