### ISSUE TITLE
Handling transient failures

### ISSUE THREAD

**Issue by danzel** [Microsoft/Cognitive-Face-Windows#45]
Would you consider a PR to handle temporary failures internally before throwing an exception?

Currently if a user calls Identify and the person group provided is being trained, that exception gets thrown out to the client app to handle.

Would it be worth handling this internally?
In EntityFramework they internally handle some errors and retry [ref](https://github.com/aspnet/EntityFrameworkCore/blob/90fc1300b4f059a6b262e960e2a3a2f091891fe4/src/EFCore.SqlServer/Storage/Internal/SqlServerTransientExceptionDetector.cs#L8)

We could do the same 
https://github.com/torutek/Cognitive-Face-Windows/commit/8f4e0434d2213c965b9ec2074c2c2758b8d708a8

**Comment by huxuan** [comment]
I agree with you to some extent. But I also think we should make this light wrapper as simple as possible. The some retry or error handling logic could be done within application side. What do you think of?

**Comment by danzel** [comment]
Yeah, either way works. Depends on the goals of the project.
If we want to just be a light wrapper then we should probably leave it as it is.

**Comment by huxuan** [comment]
Yep, actually we are already working on AutoRest generated SDK [1] though there is no commit currently. It will be more standard and lightweight.

[1] https://github.com/Azure/autorest

**Comment by danzel** [comment]
Cool thanks for the feedback :)
