### ISSUE TITLE
Project SampleUserControlLibrary is unavailable for the solution FaceAPI-WPF-Samples

### ISSUE THREAD

**Issue by ycherkes** [Microsoft/Cognitive-Face-Windows#46]
STR:
 - clone https://github.com/Microsoft/Cognitive-Face-Windows.git
 - open Cognitive-Face-Windows\Sample-WPF\FaceAPI-WPF-Samples.sln

![image](https://user-images.githubusercontent.com/13467759/35271399-ac908ef6-003a-11e8-9644-9dd88760caf6.png)

**Comment by cthrash** [comment]
Please refer to https://github.com/Microsoft/Cognitive-Face-Windows/issues/30.  Thanks

**Comment by huxuan** [comment]
Hi @ycherkes, please feel free to close this issue when problem solved. Or update when there are any further related problems.
