### ISSUE TITLE
Unable to load sample user control library

### ISSUE THREAD

**Issue by ankitkumarsingh1** [Microsoft/Cognitive-Face-Windows#47]
As i m trying to build this project, it is showing that not able to load sampleUserControlLibrary. i am new in this field,help me regarding this

**Comment by cthrash** [comment]
Please refer to [this](https://github.com/Microsoft/Cognitive-Face-Windows/issues/30) answer.

**Comment by huxuan** [comment]
Close as no further response. The link referred by @cthrash should fix the problem.
