### ISSUE TITLE
API can not work

### ISSUE THREAD

**Issue by YIFanH** [Microsoft/Cognitive-Face-Windows#52]
HI，thanks for  share the api for developers, but i can't use the api with the  Ocp-Apim-Subscription-Key，like this ：https://westus.dev.cognitive.microsoft.com/docs/services/5639d931ca73072154c1ce89/operations/563b31ea778daf121cc3a5fa/console

**Comment by lebronJ** [comment]
Hi @YIFanH , thanks for reaching us. 
1. Did you successfully get your subscription key from our [website](https://azure.microsoft.com/en-us/try/cognitive-services/?api=face-api)?
2. Are you able to [run ](https://github.com/Microsoft/Cognitive-Face-Windows#run-the-sample)the [WPF sample](https://github.com/Microsoft/Cognitive-Face-Windows/tree/master/Sample-WPF) with your subscription key?
3. Basically only one line of [code](https://github.com/Microsoft/Cognitive-Face-Windows/blob/e012a3a285249d1828ed29ce794f579d1559ba21/Sample-WPF/Controls/FaceDetectionPage.xaml.cs#L234) to init `FaceServiceClient` by subscription key and endpoint.

    `var faceServiceClient = new FaceServiceClient(subscriptionKey, endpoint);`
