### ISSUE TITLE
 FaceServiceClient(string subscriptionKey, string apiRoot) NOT Avaible in .NET SDK 1.2.1

### ISSUE THREAD

**Issue by xingzhougmu** [Microsoft/Cognitive-Face-Windows#9]
I have upgraded my SDK to 1.2.1 via nuget. But I cannot find the construction method with apiRoot arg.

I have the one with subscriptionKey only. Could you please help to take a look?
`public FaceServiceClient(string subscriptionKey)`

Below is the meta data I get from visual studio, which shows I am with 1.2.1.
```
#region Assembly Microsoft.ProjectOxford.Face, Version=1.2.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
// C:\Users\xingzhou\Desktop\VideoFace\packages\Microsoft.ProjectOxford.Face.1.2.1\lib\portable-net45+wp80+win8+wpa81+aspnetcore50\Microsoft.ProjectOxford.Face.dll
#endregion

using System;
using System.Collections.Generic;
using System.IO;
using System.Net.Http.Headers;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using Microsoft.ProjectOxford.Face.Contract;

namespace Microsoft.ProjectOxford.Face
{
    public class FaceServiceClient : IDisposable, IFaceServiceClient
    {
        public FaceServiceClient(string subscriptionKey);

        ~FaceServiceClient();
...
}
}
```

**Comment by wangjun-microsoft** [comment]
Thanks so much for your report, will fix it soon.

**Comment by xingzhougmu** [comment]
@wangjun-microsoft Thanks for the response. Do we have any ETA to fix this? Cognitive Services is just launched in Mooncake, and I would expect more and more customers starting to try this. So it's better that we could fix this asap to unblock them from the very beginning. :)

**Comment by wangjun-microsoft** [comment]
Hi Xing,

The dll has been submitted for code sign, I’ll publish the NuGet package once it is signed. ETA is tomorrow . 

Thanks

**Comment by xingzhougmu** [comment]
@wangjun-microsoft great. Thank you!

**Comment by wangjun-microsoft** [comment]
Hi Xing,
Microsoft.ProjectOxford.Face package V1.2.1.1 has been published, please have a try if you are free.
Thanks for you report again.
